export const FETCH_RANDOM_USER_REQUESTED = 'FETCH_RANDOM_USER_REQUESTED';
export const FETCH_RANDOM_USER_STARTED = 'FETCH_RANDOM_USER_STARTED';
export const FETCH_RANDOM_USER_SUCCEEDED = 'FETCH_RANDOM_USER_SUCCEEDED';
export const FETCH_RANDOM_USER_FAILED = 'FETCH_RANDOM_USER_FAILED';
export const FETCH_RANDOM_USER_FINISHED = 'FETCH_RANDOM_USER_FINISHED';
